name: OpenWrt-Lean

on:
  push:
    branches:
      - master
    #paths:
    #  - '.github/workflows/r1s_lean_h3.yml'
  schedule:
    - cron: '10 10 */4 * *'

jobs:

  build:

    runs-on: ubuntu-latest
    if: github.repository == 'coolhotsz/nanopi-test'

    steps:

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /etc/apt/sources.list.d
          sudo apt-get update
          sudo apt-get -y --no-install-recommends install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
          sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint
          
      - name: Clone Lean Source
        run: |
          mkdir Openwrt-Lean
          cd Openwrt-Lean
          git clone https://github.com/coolsnowwolf/lede
          cd lede
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          wget https://raw.githubusercontent.com/coolhhotsz/open-test/master/r1s-h3-config
          cp r1s-h3-config .config
          
      - name: Build Openwrt
        run: |
          cd /home/runner/work/open-test/open-test/Openwrt-Lean
          make -j1 V=s 
          
      - name: Zip Files
        run: |
          #gzip /home/runner/work/open-test/open-test/Openwrt-Lean/lede/bin/targets/x86/64/*.img
          find /home/runner/work/open-test/open-test/Openwrt-Lean/lede/bin/targets/x86/64/ -name "*img*" | xargs -i zip -r {}.zip {}
          
      - name: Assemble Artifact
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          find /home/runner/work/open-test/open-test/Openwrt-Lean/lede/bin/targets/x86/64/ -name "*img.zip*" | xargs -i mv -f {} ./artifact/
        
      - name: Upload Artifact
        run: |
          uses: actions/upload-artifact@master
          with: 
             name: OpenWrt-Lean-x86
             path: ./artifact/
        
        
